#!/bin/bash

dev=`/usr/bin/jack_lsp Meters:monitor_1`
while [ "$dev" == "" ] ; do
  dev=`/usr/bin/jack_lsp Meters:monitor_1`
done
/usr/bin/jack_connect Meters:monitor_12 system:playback_1
/usr/bin/jack_connect Meters:monitor_13 system:playback_2


