#!/bin/bash

set -xv

echo "Checking code repositories"
if [ -f /etc/redhat-release ] ; then
  if [ ! -f /etc/yum.repos.d/rpmfusion-free.repo ] ; then
    sudo dnf install -y http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  fi
fi

echo "Checking software"
PACKAGES="jack-audio-connection-kit vlc meterbridge xdotool ruby gcc make libxcb-devel xcb-util-devel xcb-util-wm-devel rubygems kmod-nvidia kernel-devel akmod-nvidia gcc-c++ vdpauinfo libva-vdpau-driver libva-utils xorg-x11-drv-nvidia-libs rubygem-eventmachine vlc-plugin-jack"
# Make sure the prerequisite software is installed
if [ -f /usr/bin/apt-get ] ; then
    for PACKAGE in $PACKAGES ; do
        if ! dpkg -l $PACKAGE > /dev/null ; then
            sudo apt-get install -y $PACKAGE
        fi
    done
elif [ -f /usr/bin/dnf ] ; then
    for PACKAGE in $PACKAGES ; do
        if [ -z "`rpm -qa $PACKAGE`" ] ; then
            sudo dnf -y install $PACKAGE
        fi
    done
elif [ -f /usr/bin/yum ] ; then
    for PACKAGE in $PACKAGES ; do
        if [ -z "`rpm -qa $PACKAGE`" ] ; then
            sudo yum -y install $PACKAGE
        fi
    done
else
    echo "This OS not supported"
    exit 1
fi

echo "Checking configurations"
if [ ! -f /etc/security/limits.d/95-jack.conf ] ; then
cat > /tmp/95-jack.conf <<EOF
# Default limits for users of jack-audio-connection-kit

@jackuser - rtprio 70
@jackuser - memlock unlimited

@pulse-rt - rtprio 20
@pulse-rt - nice -20
EOF
sudo mv /tmp/95-jack.conf /etc/security/limits.d/95-jack.conf
sudo chown root.root /etc/security/limits.d/95-jack.conf
sudo chmod 644 /etc/security/limits.d/95-jack.conf
fi
if ! grep --quiet jackuser /etc/group ; then
    sudo sed -i'' '$ a\
jackuser:x:981:monitor' /etc/group
fi
if [ ! -f /etc/security/limits.d/20-nproc.conf ] ; then
cat > /tmp/20-nproc.conf <<EOF
# Default limit for number of user's processes to prevent
# accidental fork bombs.
# See rhbz #432903 for reasoning.

*          soft    nproc     4096
root       soft    nproc     unlimited
EOF
sudo mv /tmp/20-nproc.conf /etc/security/limits.d/20-nproc.conf
sudo chown root.root /etc/security/limits.d/20-nproc.conf
sudo chmod 644 /etc/security/limits.d/20-nproc.conf
fi

